name: vecinapp
description: 'Herramientas de organización para Vecinos.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

# See https://pub.dev/documentation/meta/latest/meta/requiredEnvironment.html
environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
