name: vecinapp
description: 'Herramientas de organización para Vecinos.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

# See https://pub.dev/documentation/meta/latest/meta/requiredEnvironment.html
environment:
  sdk: ^3.5.1

dependencies:
  bloc: 9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.3.0
  equatable: ^2.0.5
  firebase_app_check: ^0.3.2+8
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_image_compress: ^2.3.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.0.0
  intl: ^0.20.0
  path_provider: ^2.1.4
  share_plus: ^11.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
